#!/bin/bash

DOTFILES=$HOME/.dotfiles
#test

# Bash completion (installed via Homebrew; source after `brew` is added to PATH)
[ -r "$(brew --prefix)/etc/bash_completion" ] && source "$(brew --prefix)/etc/bash_completion"

export PATH="\
$HOME/bin:\
/usr/local/bin:\
/usr/local/share/python:\
/usr/local/share/npm/bin:\
/Users/tonatiuh/.dotfiles/git/extensions:\
$HOME/.rbenv/bin:\
/usr/local/heroku/bin:/usr/local/bin:/Users/tonatiuh/.rvm/gems/ruby-1.9.3-p194/bin:/Users/tonatiuh/.rvm/gems/ruby-1.9.3-p194@global/bin:/Users/tonatiuh/.rvm/rubies/ruby-1.9.3-p194/bin:/Users/tonatiuh/.rvm/bin:/Users/tonatiuh/.rvm/gems/ruby-1.9.3-p125-perf/bin:/usr/bin:/Users/tonatiuh/.rvm/gems/ruby-1.9.3-p448@thrive/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/X11/bin:/Users/tonatiuh/.gh-dotfiles/bin \
$PATH:\
/Users/tonatiuh/.rvm/rubies/ruby-1.9.3-p125-perf/bin/ruby:/Users/tonatiuh/.rvm/gems/ruby-1.9.3-p125-perf/bin:\
"&>/dev/null

source /Users/tonatiuh/.rvm/scripts/rvm

# Load files
files=(bash_functions bash_aliases bash_exports)
alias pr="pry-remote"
alias irc="rails console"

for file in ${files[@]}; do
  file="$DOTFILES/bash/$file"
  [ -e "$file" ] && source "$file"
done

# Choose prompt theme
source "$DOTFILES/bash/prompt_minimalist"

bind -f $DOTFILES/bash/bash_bindings


# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# append to the history file, don't overwrite it
shopt -s histappend >/dev/null 2>&1

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# no duplicates in bash history and ignore same sucessive entries.
set match-hidden-files off
set page-completions off
# set completion-query-items 350

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Autocomplete for 'g' as well
complete -o default -o nospace -F _git g

if [ -f ~/.git-completion.bash  ]; then
  . ~/.git-completion.bash
fi

export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"'

# load direnv https://github.com/zimbatm/direnv
eval "$(direnv hook bash)"
