#!bin/bash
# Prompt

function git_branch {
  git branch 2>/dev/null | grep -e '\*' | sed 's/^..\(.*\)/\\[ \\]\1/'
}

function prompt {
  local BGBLACK="\[\033[40m\]"
  local BGRED="\[\033[41m\]"
  local BGGREEN="\[\033[42m\]"
  local BGYELLOW="\[\033[43m\]"
  local BGBLUE="\[\033[44m\]"
  local BGMAGENTA="\[\033[45m\]"
  local BGCYAN="\[\033[46m\]"
  local BGWHITE="\[\033[47m\]"
  local BGTRANS="\[\033[49m\]"

  local BLACK="\[\033[30m\]"
  local RED="\[\033[31m\]"
  local GREEN="\[\033[32m\]"
  local YELLOW="\[\033[1;33m\]"
  local BLUE="\[\033[34m\]"
  local MAGENTA="\[\033[35m\]"
  local CYAN="\[\033[36m\]"
  local WHITE="\[\033[37m\]"
  local TRANS="\[\033[39m\]"

  local BOLD="\[\033[1m\]"
  local RESET="\[\033[0m\]"
  local GRAY="\[\033[49;30m\]"

  export PS1="\n\n$BGGREEN $WHITE\$(__git_ps1 '%s') $BGCYAN \u / tonatiuh $GRAY \w \n\n$YELLOW > $RESET"
}

prompt
